# Generated by Django 6.0.3 on 2026-04-09 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_cart_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="barangay",
        ),
        migrations.RemoveField(
            model_name="order",
            name="city",
        ),
        migrations.RemoveField(
            model_name="order",
            name="phone",
        ),
        migrations.RemoveField(
            model_name="order",
            name="province",
        ),
        migrations.AddField(
            model_name="order",
            name="email",
            field=models.EmailField(default="unknown@example.com", max_length=254),
            preserve_default=False,
        ),
    ]
