# Generated by Django 6.0.3 on 2026-04-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0004_remove_order_address_remove_order_barangay_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="download_link",
            field=models.URLField(
                blank=True,
                help_text="Google Drive direct download link for the software product",
                max_length=500,
                null=True,
            ),
        ),
    ]
